name: Create and publish a Docker image

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: ['master']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Inject secrets - REDDIT_USERNAME
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "REDDIT_USERNAME"
          replace: "${{ secrets.REDDIT_USERNAME }}"
      - name: Inject secrets - REDDIT_PASSWORD
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "REDDIT_PASSWORD"
          replace: "${{ secrets.REDDIT_PASSWORD }}"
      - name: Inject secrets - CLIENT_ID
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "CLIENT_ID"
          replace: "${{ secrets.CLIENT_ID }}"
      - name: Inject secrets - CLIENT_SECRET
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "CLIENT_SECRET"
          replace: "${{ secrets.CLIENT_SECRET }}"
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
